services:
  my-alooha-chat:
    build:
      context: .
    container_name: my-alooha-chat
    volumes:
      - './:/home/myaloohachat/app'
    working_dir: /home/myaloohachat/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=${PORT:-8080}
    ports:
      - "${PORT:-8199}:${PORT:-8199}"
